<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_movie</name>
   <tag></tag>
   <elementGuidId>a7019caf-8691-4cd4-bd9a-7207f762142e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#movie</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'movie']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>51477479-beeb-4192-8de0-e066642ae230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>movie</value>
      <webElementGuid>3cf9bc13-0d86-4761-92d1-7407958e13ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/movie?query=Aven</value>
      <webElementGuid>b395ebed-5634-400b-a49c-b7f3c72a1040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search_tab </value>
      <webElementGuid>4872d057-b3c3-4ec9-8f1a-e7ba1c481771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Movies</value>
      <webElementGuid>f75ad84d-d61d-46d2-9806-3919a55e5633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Movies</value>
      <webElementGuid>d9e874df-73ef-4b64-b089-6f993c0b775f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Movies</value>
      <webElementGuid>ccc64ea3-a746-437e-844c-420d36608ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-de6f3b612e957c67bd0175964a478d2d</value>
      <webElementGuid>edb9e0fa-795d-4322-8074-1aa0d989a85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'movie']</value>
      <webElementGuid>b7eefcfa-0ed2-4fc8-812f-3b60625a0141</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'movie']</value>
      <webElementGuid>ae60180d-13dc-4ac3-a86e-b00f5730825d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'movie' and @href = '/search/movie?query=Aven' and @title = 'Movies' and @alt = 'Movies' and (text() = 'Movies' or . = 'Movies')]</value>
      <webElementGuid>5df64f97-e4b0-4b43-88b9-e360a60cf3c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
