<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_The Movie Database (TMDB)</name>
   <tag></tag>
   <elementGuidId>f7ca7b57-3417-45c8-98b3-0ee14da2db7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Home']//*[@alt = 'The Movie Database (TMDB)']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@alt = 'The Movie Database (TMDB)' and @src = '/assets/2/v4/logos/v2/blue_short-8e7b30f73a4020692ccca9c88bafe5dcb6f8a62a4c6bc55cd9ba82bb2cd95f6c.svg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Home&quot;] [alt=&quot;The\ Movie\ Database\ \(TMDB\)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>23971d27-19d6-47d3-ac83-f0b8aded82d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>The Movie Database (TMDB)</value>
      <webElementGuid>7a169c1a-4219-40ab-8e60-22aa7d2180b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>154</value>
      <webElementGuid>4bb7e5d6-3550-4234-a20a-cb922b2de70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>635f1142-489d-4cff-b45f-7740886cc9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/2/v4/logos/v2/blue_short-8e7b30f73a4020692ccca9c88bafe5dcb6f8a62a4c6bc55cd9ba82bb2cd95f6c.svg</value>
      <webElementGuid>534c94ca-acb7-4c69-919d-3961f4b18b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-57152e8a4e4ef8e7055cf8f7f034c9a1</value>
      <webElementGuid>496b1588-f96b-4eb7-b617-697a140fe600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Home']//*[@alt = 'The Movie Database (TMDB)']</value>
      <webElementGuid>87c50f88-bb20-400c-a222-19c83865ca2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Home']//*[@alt = 'The Movie Database (TMDB)']</value>
      <webElementGuid>34fcc3aa-ed74-4758-87e4-bbf480f1d82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'The Movie Database (TMDB)' and @src = '/assets/2/v4/logos/v2/blue_short-8e7b30f73a4020692ccca9c88bafe5dcb6f8a62a4c6bc55cd9ba82bb2cd95f6c.svg']</value>
      <webElementGuid>5d71c949-9beb-4e4d-a4cd-b558f8b4bfc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
