<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Bloodhounds</name>
   <tag></tag>
   <elementGuidId>7f757193-4075-4408-a6ea-7c4fdc65b70a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@alt = 'Bloodhounds']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[alt=&quot;Bloodhounds&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>903ba9e1-80ff-42e4-abce-54e5595fb3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>c3e74455-5d38-478d-a7a2-93a89a676841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>poster w-full</value>
      <webElementGuid>06308baa-e0eb-475f-8794-8bd7f380d65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.themoviedb.org/t/p/w220_and_h330_face/kxU1hhebWZGaz8gkMVi8zkZhzVt.jpg</value>
      <webElementGuid>c16c2d48-cdad-4530-8bb6-ed6a53df897f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://media.themoviedb.org/t/p/w220_and_h330_face/kxU1hhebWZGaz8gkMVi8zkZhzVt.jpg 1x, https://media.themoviedb.org/t/p/w440_and_h660_face/kxU1hhebWZGaz8gkMVi8zkZhzVt.jpg 2x</value>
      <webElementGuid>f8f1ca93-55a1-4898-b86c-028e88587d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bloodhounds</value>
      <webElementGuid>3ce63ca7-ddaa-4b39-8cb0-5ffd0cbce370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a9fcc1715a2ac2fe07bd386a6d71d3b0</value>
      <webElementGuid>d2b83270-c0dd-4e6c-9e56-f0ff601ebd0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@alt = 'Bloodhounds']</value>
      <webElementGuid>805b4c29-8c5b-48d0-b1fa-5fe1a5aa68ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@alt = 'Bloodhounds']</value>
      <webElementGuid>464770da-13bf-40bc-80ff-e1a7970c08af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.themoviedb.org/t/p/w220_and_h330_face/kxU1hhebWZGaz8gkMVi8zkZhzVt.jpg' and @alt = 'Bloodhounds']</value>
      <webElementGuid>ab8613ce-f565-4e11-80fa-e51173a58692</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
