<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_keyword</name>
   <tag></tag>
   <elementGuidId>11538f39-5b41-40e2-9103-de27c042ddf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'keyword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#keyword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ebfe9c7b-eaef-4b4e-a141-aa45dc171df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keyword</value>
      <webElementGuid>cadfb2da-f63e-46c2-ac09-42c8c911c2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/keyword?query=2026</value>
      <webElementGuid>b719094b-ba49-403b-9257-9d5cdc1261a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search_tab</value>
      <webElementGuid>727f1bad-f67a-4084-8682-d893e32d5670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Keywords</value>
      <webElementGuid>6a5886ee-78cc-411e-ba44-9a33cd2e0458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Keywords</value>
      <webElementGuid>0e127feb-c8ed-4b75-b664-4ef5b37c0003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keywords</value>
      <webElementGuid>0878c106-02d2-4548-89fe-49818be99bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-45b4b8072626ed5be946639def399f86</value>
      <webElementGuid>d4c6858e-6807-490f-8ad0-98510f1907c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'keyword']</value>
      <webElementGuid>ead0b599-35d4-479f-b8b4-6a42649edd20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'keyword']</value>
      <webElementGuid>5edcff69-d893-4f49-9f2b-c89e55248172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'keyword' and @href = '/search/keyword?query=2026' and @title = 'Keywords' and @alt = 'Keywords' and (text() = 'Keywords' or . = 'Keywords')]</value>
      <webElementGuid>562ef734-717b-4ad6-abd9-28230216d5b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
