<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_movie</name>
   <tag></tag>
   <elementGuidId>99c86ee0-3141-432b-bbb1-d2960d4ad269</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'movie']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#movie</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>802ea449-4e93-40c2-a983-18e12f327e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>movie</value>
      <webElementGuid>cf147cb5-e279-4915-802c-5c6b99b0d08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/movie?query=2026</value>
      <webElementGuid>dc205c24-e10e-4a39-bf37-ab997150845c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search_tab </value>
      <webElementGuid>34d1b77f-de17-4a14-b3e1-946d61f28b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Movies</value>
      <webElementGuid>b22afd4e-81bd-4955-a0d3-ed554fb507e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Movies</value>
      <webElementGuid>c914fe99-6605-4bf0-9a0f-58fcd388c29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Movies</value>
      <webElementGuid>7c0daefd-3c68-47a8-b58d-786330a871c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-de6f3b612e957c67bd0175964a478d2d</value>
      <webElementGuid>cf799b22-fdeb-437e-90f8-b3c56eb2e9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'movie']</value>
      <webElementGuid>e7261576-1678-4579-81d2-edc0db7e284a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'movie']</value>
      <webElementGuid>c0af0374-c03a-4fcd-b70b-df6601a9fa5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'movie' and @href = '/search/movie?query=2026' and @title = 'Movies' and @alt = 'Movies' and (text() = 'Movies' or . = 'Movies')]</value>
      <webElementGuid>9adbf54a-8a8d-4b80-bcfa-83db01ef56c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
