<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_watchlist</name>
   <tag></tag>
   <elementGuidId>4add6557-e463-4ef6-a17a-75be9a95c929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'watchlist']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#watchlist</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>afa35034-6125-4f17-af51-016b98f45f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>watchlist</value>
      <webElementGuid>450e0613-2abf-4b15-a004-c0c716be2c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no_click add_to_account_list watchlist</value>
      <webElementGuid>8faf7673-eac5-4707-afde-7a2280b0b910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c66490b0-6fc9-43cf-9977-9a7ac32c427b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-583bb7bca0d630ac3340fd9490a277b4</value>
      <webElementGuid>bfd8f193-20fb-43cf-8aa6-2d0c36ddd643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'watchlist']</value>
      <webElementGuid>01ceb086-3500-4fa0-8d63-a6019f321dc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'watchlist']</value>
      <webElementGuid>e22b902e-6359-4845-a3af-ea24d054eade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'watchlist' and @href = '#']</value>
      <webElementGuid>9761ed80-11da-42fb-818d-0e64aa465ecc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
