<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_backdrops</name>
   <tag></tag>
   <elementGuidId>13625825-d15c-4870-898c-a87e7ff0c7e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'backdrops']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#backdrops</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a81414e8-c0fa-40e5-8b9d-5a756dc42cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>backdrops</value>
      <webElementGuid>45ac0559-4d8b-4a23-8304-18559de3877d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>media_panel</value>
      <webElementGuid>002e71b3-bab0-42d2-84f3-4e2eefd3e01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>79885417-9b91-46dc-a997-cbcafd7919a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Backdrops 99</value>
      <webElementGuid>3fff3a00-246d-49d1-839f-1cddddfe8e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-251427c38f6a0ca1fed45e6eafee5ca2</value>
      <webElementGuid>c6e51539-5b85-4230-aecb-d392da12468b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'backdrops']</value>
      <webElementGuid>3c223cad-3448-4ba6-9570-bb22a8bcdbb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'backdrops']</value>
      <webElementGuid>9e0ad3ed-b04e-47e3-b819-c459691ca829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'backdrops' and @href = '#' and (text() = 'Backdrops 99' or . = 'Backdrops 99')]</value>
      <webElementGuid>afcaddec-780a-474d-b688-17aba1f30771</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
