<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_player-controls-background</name>
   <tag></tag>
   <elementGuidId>38426c08-f706-4a6e-92cd-b93d7579421f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' player-controls-background ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' player-controls-background ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.player-controls-background</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d8fc58cf-f920-4831-bb6d-2aaf958ce13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>player-controls-background</value>
      <webElementGuid>b67a07db-1209-4a26-9878-75262e3cb453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-84bb7c92c4dcd3cc25320dbdcfca4d71</value>
      <webElementGuid>00d32096-6958-4c94-9310-b4e7e96e63b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' player-controls-background ')]</value>
      <webElementGuid>6738fc68-ce8e-4fda-a3a7-3793562f1dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Avatar La v Tro Tn (2025)  The Movie D_a1a082/iframe_iframe</value>
      <webElementGuid>28ba749f-c4ba-433c-82ae-e66ef1f20bd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' player-controls-background ')]</value>
      <webElementGuid>fe46f380-5229-440a-b450-bd4c83cf041d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
