<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_player-controls-background</name>
   <tag></tag>
   <elementGuidId>38426c08-f706-4a6e-92cd-b93d7579421f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' player-controls-background ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.player-controls-background</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19e9441b-5b10-4446-b4d9-15a9d239c223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>player-controls-background</value>
      <webElementGuid>d736025b-2bed-4955-b53b-cfec2a8b8447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-84bb7c92c4dcd3cc25320dbdcfca4d71</value>
      <webElementGuid>72cb1afd-eb12-48dd-9392-0b37d0688f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' player-controls-background ')]</value>
      <webElementGuid>97068fc3-4ce6-41a2-9bb7-a2baffc9162a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Avatar La v Tro Tn (2025)  The Movie D_a1a082/iframe_iframe</value>
      <webElementGuid>d1f052a7-273f-460c-aef3-e7c4e86b3649</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' player-controls-background ')]</value>
      <webElementGuid>0e5217f6-df64-4fb8-bbb8-f99cc654c0dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
