<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_iframe</name>
   <tag></tag>
   <elementGuidId>c46c8cdb-3b66-4fc4-8cc3-b29afb8c459d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@allowfullscreen = '']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[allowfullscreen=&quot;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4695e349-ce10-4565-ab6f-c282a68f1ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text/html</value>
      <webElementGuid>e2b2af17-c6d0-44e9-81ea-dbc51d38ed46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>932</value>
      <webElementGuid>0045edaf-0937-4d08-b4b3-81ca81e5cbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>524</value>
      <webElementGuid>4c3b9549-0ffd-452d-a482-92a2d5d01450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//www.youtube.com/embed/wIiASgAkk7g?autoplay=1&amp;origin=https%3A%2F%2Fwww.themoviedb.org&amp;hl=vi&amp;modestbranding=1&amp;fs=1&amp;autohide=1</value>
      <webElementGuid>1cf01c3c-7555-4462-8395-2946fa4de664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5306789d-4d3b-4ef5-90ce-3f88243ccad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-954024909d6e7060f5b7c4c5869ca1bb</value>
      <webElementGuid>a3479f14-910c-47cc-b0dc-3728e8747da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@allowfullscreen = '']</value>
      <webElementGuid>7984bd0b-a008-415c-a1fd-5a89882ee692</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@allowfullscreen = '']</value>
      <webElementGuid>568a0bd3-da0d-4698-85ad-667b9a4b84fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@type = 'text/html' and @src = '//www.youtube.com/embed/wIiASgAkk7g?autoplay=1&amp;origin=https%3A%2F%2Fwww.themoviedb.org&amp;hl=vi&amp;modestbranding=1&amp;fs=1&amp;autohide=1']</value>
      <webElementGuid>b390ee51-ff10-40e6-9b01-8a2167c49237</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
