<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_iframe</name>
   <tag></tag>
   <elementGuidId>c46c8cdb-3b66-4fc4-8cc3-b29afb8c459d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@allowfullscreen = '']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[allowfullscreen=&quot;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>68eb156b-97bb-4459-9735-9c731a10493c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text/html</value>
      <webElementGuid>46b5c0b0-867f-496a-ae4e-f3e4325366bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>932</value>
      <webElementGuid>e596748d-4d53-420d-b6ac-6924fc603993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>524</value>
      <webElementGuid>0e221a78-6d88-4ec8-94f7-a5d689a4bfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//www.youtube.com/embed/wIiASgAkk7g?autoplay=1&amp;origin=https%3A%2F%2Fwww.themoviedb.org&amp;hl=vi&amp;modestbranding=1&amp;fs=1&amp;autohide=1</value>
      <webElementGuid>59f75dd2-9131-4558-a89e-969b93101803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>951bb669-4920-4437-a26f-d61b4c6553cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-954024909d6e7060f5b7c4c5869ca1bb</value>
      <webElementGuid>f678dcba-2f7d-4964-9f62-62a2eff5ea04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@allowfullscreen = '']</value>
      <webElementGuid>db6ec32a-279d-451c-8eac-eade7df24450</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@allowfullscreen = '']</value>
      <webElementGuid>fdc7331a-c116-41f7-99b7-82f1df82f7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@type = 'text/html' and @src = '//www.youtube.com/embed/wIiASgAkk7g?autoplay=1&amp;origin=https%3A%2F%2Fwww.themoviedb.org&amp;hl=vi&amp;modestbranding=1&amp;fs=1&amp;autohide=1']</value>
      <webElementGuid>7af0d30a-7e95-4cb4-8c8e-2b0846d1e84b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
