<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Movies</name>
   <tag></tag>
   <elementGuidId>feb2e61c-612e-488d-afe6-035a32447f83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/u/Alver_John/favorites']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/u\/Alver_John\/favorites&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4bed7f76-e3dd-4036-a907-09a7b106a5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/u/Alver_John/favorites</value>
      <webElementGuid>38e49b6f-eb0a-410c-991c-e98c48d731b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link k-menu-link</value>
      <webElementGuid>e7d15534-5be8-48a2-a2fc-f03049e9ebfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Movies</value>
      <webElementGuid>a37b1bfc-5414-4c92-b4f8-252a70e539b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fe625d27cf153afcfd22d81c61ccb455</value>
      <webElementGuid>812d0b4d-535a-4485-855f-c073d70eee39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/u/Alver_John/favorites']</value>
      <webElementGuid>2ad23a89-f05d-4634-82d2-510adcda8310</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/u/Alver_John/favorites']</value>
      <webElementGuid>8cbcb702-f05b-4870-801e-c7f7ed5c769b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/u/Alver_John/favorites' and (text() = 'Movies' or . = 'Movies')]</value>
      <webElementGuid>ceccf0f3-7f63-46a1-b7f6-a57902ae9435</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
