<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>c197ae63-58d1-4983-b42a-1055de63e293</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' tv ')]//*[(name() = 'a') and (position() = 3)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.tv a:nth-child(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc6094ae-f13e-4a5d-8bd2-dc02719b3e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/tv?query=a&amp;page=2</value>
      <webElementGuid>36562fc6-c3f3-4f53-a6c5-946f413966d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>fe555202-d68f-49ca-9567-5e6053ab326e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0e7eac9c950756cb21a3e11abbb2609b</value>
      <webElementGuid>0cd260c9-e6e6-4587-8e7a-7032c3eeff54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' tv ')]//*[(name() = 'a') and (position() = 3)]</value>
      <webElementGuid>e6dc0490-63c8-45b8-a5ba-3e2df3c82328</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' tv ')]//*[(name() = 'a') and (position() = 3)]</value>
      <webElementGuid>a8535a3e-eb3f-479d-9e1d-d26ba2e9d658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search/tv?query=a&amp;page=2' and (text() = '2' or . = '2')]</value>
      <webElementGuid>a686c7eb-924c-4c19-ae49-c098026c54f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
