<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_award</name>
   <tag></tag>
   <elementGuidId>94a8e818-bc5e-45af-9899-1687ede47b5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'award']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#award</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>80ce084d-b8a1-4852-9280-a018aaaa9986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>award</value>
      <webElementGuid>e98b063c-9edc-46f9-bbab-7a165707f69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/award?query=a</value>
      <webElementGuid>5c6ea6a8-7923-4b9e-878c-fd1c54e13ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search_tab</value>
      <webElementGuid>051b1382-3fde-45b0-b43c-b97499ba1413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Awards</value>
      <webElementGuid>fe6fe040-4542-4412-ba13-998146ea5458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Awards</value>
      <webElementGuid>336fe0ba-b7ef-48b9-bc7d-c4536d59a857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Awards</value>
      <webElementGuid>b52caef2-31e0-402a-9dbb-f050c4c6d83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-adcba49bf4221aa08b75dcafb4fe2e66</value>
      <webElementGuid>7cabef24-f9dd-4154-a86e-29ed3e1902cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'award']</value>
      <webElementGuid>6add6973-14a0-4024-a546-c8a8f3b8b6f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'award']</value>
      <webElementGuid>8efd0b54-8611-4c8e-9ea4-ebf7b4cfc033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'award' and @href = '/search/award?query=a' and @title = 'Awards' and @alt = 'Awards' and (text() = 'Awards' or . = 'Awards')]</value>
      <webElementGuid>e394e59a-80f5-4489-bf52-ecdae5ee4b52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
