<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_collection</name>
   <tag></tag>
   <elementGuidId>d05793d1-93b2-40f5-bfb6-503eaa0c707a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'collection']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#collection</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>11ed3715-9c9a-451e-aef7-1cd334b3d82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>collection</value>
      <webElementGuid>888bc655-2eb8-4310-a1b2-6f6232076583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/collection?query=a</value>
      <webElementGuid>2e4d7fd9-670a-4e79-93ff-68f40a02bbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search_tab</value>
      <webElementGuid>b17327ef-da0f-457b-b12d-3376a7a43374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Collections</value>
      <webElementGuid>9aa5135d-d4d6-4432-8858-47ac0dd52b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Collections</value>
      <webElementGuid>27ad1fbe-2cf5-4fa5-9d62-1acbf0bf1d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Collections</value>
      <webElementGuid>1ea86079-5c17-4d9b-b96d-4b3aa96b07cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b68306ee13398ef800f1c4cc9a631ad0</value>
      <webElementGuid>6f23c634-fa58-4853-bc76-b6f5c7704dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'collection']</value>
      <webElementGuid>efdf707f-e27d-470e-9087-d0877e8e9dc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'collection']</value>
      <webElementGuid>73878aef-c809-4512-94c8-8a2c6df3d97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'collection' and @href = '/search/collection?query=a' and @title = 'Collections' and @alt = 'Collections' and (text() = 'Collections' or . = 'Collections')]</value>
      <webElementGuid>40f57cc8-a2fd-4758-86ba-4f0a9a5e5642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
