<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_movie</name>
   <tag></tag>
   <elementGuidId>bde01a48-1dc2-44b2-a9e4-6ae283e9426b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'movie']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#movie</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7b2cced0-e6e6-4269-b1a1-209a4d1e39d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>movie</value>
      <webElementGuid>b7dd4a73-a7ba-42c8-b92a-deee85aebeb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/movie?query=a</value>
      <webElementGuid>97e862b9-e102-4dbb-87d8-c691344e6def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search_tab </value>
      <webElementGuid>6efbf63b-5298-44f5-ab5d-414735188785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Movies</value>
      <webElementGuid>2a8458e5-9f8b-4064-a61a-63317dd9e4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Movies</value>
      <webElementGuid>07ee33a0-975c-485d-bff3-ad6b00bef00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Movies</value>
      <webElementGuid>e82cd9f8-2961-4308-bc57-51713050474e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-de6f3b612e957c67bd0175964a478d2d</value>
      <webElementGuid>5f968961-27f7-42bf-85ca-fbc74f37e50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'movie']</value>
      <webElementGuid>6299e5dc-562a-49f4-abd5-50bdf1c2f433</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'movie']</value>
      <webElementGuid>9198e735-f690-48a0-9c82-1b1ed406b565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'movie' and @href = '/search/movie?query=a' and @title = 'Movies' and @alt = 'Movies' and (text() = 'Movies' or . = 'Movies')]</value>
      <webElementGuid>bcfc4d65-ac19-490b-9937-8a0a1d2a2f15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
