<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_network</name>
   <tag></tag>
   <elementGuidId>a566a0f1-dfff-4d78-b670-ce6d435c3228</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'network']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#network</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>69417270-21ba-4e36-9d92-d3dc4218b795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>network</value>
      <webElementGuid>ac4d45de-3f45-4e8c-a831-8e30e44e57a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/network?query=a</value>
      <webElementGuid>213cce05-d992-46ea-8026-8dba174eb643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search_tab</value>
      <webElementGuid>e6b66638-f857-4458-a08b-3f9fd4a964fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Networks</value>
      <webElementGuid>1a18d4ed-7c5f-4770-8ced-c373bb2bb731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Networks</value>
      <webElementGuid>a9002d13-45da-4e31-8b14-f7444f02fda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Networks</value>
      <webElementGuid>819bd2a6-984d-440b-8daf-da2723076074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3408718f9c0d1cfaa8dcc837cd2dc17b</value>
      <webElementGuid>c5184ddd-70ed-4b9a-b554-0f34c14148b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'network']</value>
      <webElementGuid>dfed3efb-c179-4081-a11d-32f3a7208d15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'network']</value>
      <webElementGuid>d1587ba3-ab90-4ced-9c3f-98e66cfae63a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'network' and @href = '/search/network?query=a' and @title = 'Networks' and @alt = 'Networks' and (text() = 'Networks' or . = 'Networks')]</value>
      <webElementGuid>de1c2587-7d69-4165-b043-58121501240c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
