<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Next</name>
   <tag></tag>
   <elementGuidId>e6e2716e-7394-4ecb-a754-b33d193110ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.person [aria-label=&quot;Next&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' person ')]//*[@aria-label = 'Next']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c3200afc-f86a-4123-ab4d-cf2e2f9c2b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/person?query=a&amp;page=2</value>
      <webElementGuid>376c0be8-a8b4-4dd7-90c4-0e307653f100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>7e912a28-0d1f-48eb-ae86-b462416c2230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next →</value>
      <webElementGuid>c908e4e5-0efa-4ab7-b621-6f9fe7507475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d2ff2653f1f3789157b410bcefd90148</value>
      <webElementGuid>162679f5-cae8-4d84-876b-c89d2c7034ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' person ')]//*[@aria-label = 'Next']</value>
      <webElementGuid>e2c96e1a-7d7c-4406-b8f4-c92133e5a086</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' person ')]//*[@aria-label = 'Next']</value>
      <webElementGuid>ef946002-5b15-44b1-9823-a9595429b8c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search/person?query=a&amp;page=2' and (text() = 'Next →' or . = 'Next →')]</value>
      <webElementGuid>ea6810ae-f7b7-4d64-9978-0fd9d2e2f2b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
