<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_person</name>
   <tag></tag>
   <elementGuidId>af65729f-24f1-4315-a63e-55fd27359f05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'person']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#person</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>55f5ca4e-8e8c-4e52-8f27-35d36ad015da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>person</value>
      <webElementGuid>22268d40-75f4-4836-9b04-6eb0922583db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search/person?query=a</value>
      <webElementGuid>1d4ceecf-73f6-45cc-905b-b0ca1693d2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search_tab </value>
      <webElementGuid>8ecee703-8eaa-4539-9a5c-6a364b12d700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>People</value>
      <webElementGuid>3bb42535-46b9-4322-bbbf-cf99c4739b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>People</value>
      <webElementGuid>fca31056-d8b3-47f0-8a99-6e2deafeeed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>People</value>
      <webElementGuid>6270b828-c388-41fe-962a-72701457835b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-bc27d8285f1caa96bbec7c528e4e8099</value>
      <webElementGuid>9a11f6ff-34a9-405a-9a0b-df3e80f9a916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'person']</value>
      <webElementGuid>6f4abd16-9cdf-4f40-941d-d4fc08a46465</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'person']</value>
      <webElementGuid>0133348a-bf5a-42e6-839c-27b80bf9e7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'person' and @href = '/search/person?query=a' and @title = 'People' and @alt = 'People' and (text() = 'People' or . = 'People')]</value>
      <webElementGuid>e255e2f8-6f63-43c8-be51-9fef0002ba5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
