<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_favourite</name>
   <tag></tag>
   <elementGuidId>abcabb18-6b33-411c-ad1b-90f301d0fd29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'favourite']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#favourite</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d8d32765-73da-43ac-860b-7c27ec1e3e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>favourite</value>
      <webElementGuid>e15ec860-5d3c-4ed3-a0b5-004ad0ef22e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no_click add_to_account_list favourite</value>
      <webElementGuid>21195720-690d-4e26-8ac7-c2ac91c63f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a1cbb6bc-0780-42c2-8f24-49b7c626b2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ef2be003e86bd531ec17c87383c19375</value>
      <webElementGuid>e56efaf7-5bf3-4ef0-81a1-31d58b1d3973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'favourite']</value>
      <webElementGuid>b030c00f-3070-46b8-a4c5-ddad3c2ea04d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'favourite']</value>
      <webElementGuid>598cc868-6e74-42f0-a993-f95bf47baa48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'favourite' and @href = '#']</value>
      <webElementGuid>c2266ddd-8dd2-4183-8ee8-8a160c2a615a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
