<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_watchlist</name>
   <tag></tag>
   <elementGuidId>2a5f3abf-c817-4068-9cce-ddef83b4b22f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'watchlist']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#watchlist</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>27a73180-2579-4362-b8d2-ac6273591074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>watchlist</value>
      <webElementGuid>100df50c-2a08-4fc8-8c11-de2d845524d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>no_click add_to_account_list watchlist</value>
      <webElementGuid>1c6868d7-1bfa-4964-b185-62d02697ab85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>79b40d55-aa6b-4164-9a15-bf05c5496156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-583bb7bca0d630ac3340fd9490a277b4</value>
      <webElementGuid>5b38d951-f842-4bf2-a33c-e3af1ff65891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'watchlist']</value>
      <webElementGuid>c01638b6-9051-49da-a335-bed564bdb8a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'watchlist']</value>
      <webElementGuid>696d2125-18ec-4b61-857a-371b87e7bde7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'watchlist' and @href = '#']</value>
      <webElementGuid>755da915-59d7-4835-9227-8d14b8fb98fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
