<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_onetrust-accept-btn-handler</name>
   <tag></tag>
   <elementGuidId>ba9b03f4-47ea-4158-a701-135cab0a7c8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'onetrust-accept-btn-handler']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'onetrust-accept-btn-handler' and (text() = 'Chấp nhận mọi cookie' or . = 'Chấp nhận mọi cookie')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#onetrust-accept-btn-handler</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>369c4e40-06df-4794-b988-4b0028ffc0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onetrust-accept-btn-handler</value>
      <webElementGuid>04f4bd22-fc59-4733-89b2-c6e5b45d7e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chấp nhận mọi cookie</value>
      <webElementGuid>47ac3d33-ca4e-4024-b9a2-9d0c5afb2cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-303d1babeaf3338b5aa466cabd4a85ea</value>
      <webElementGuid>0c65ca1e-3146-4774-a55e-c435b0596d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'onetrust-accept-btn-handler']</value>
      <webElementGuid>0336f54f-51d3-4188-9ab1-3148457673c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'onetrust-accept-btn-handler']</value>
      <webElementGuid>554eb483-897b-4b5b-b59e-2b366c3221e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'onetrust-accept-btn-handler' and (text() = 'Chấp nhận mọi cookie' or . = 'Chấp nhận mọi cookie')]</value>
      <webElementGuid>541fd1a2-f774-46be-a5dc-71e8ebcc4f07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
